Repository SSAMBBONG/cs-database, pull requests merged in 2024-06, with the labels that each got.

#1 lecture14~18
  심종한/[lecture14] transaction/README.md
  심종한/[lecture14] transaction/isolation필요성.png
  심종한/[lecture15] concurrency control 기초 (serializability)/README.md
  심종한/[lecture15] concurrency control 기초 (serializability)/conflict operation 순서바뀜.png
  심종한/[lecture15] concurrency control 기초 (serializability)/conflict 종류.png
  심종한/[lecture15] concurrency control 기초 (serializability)/lostupdate현상.png
  심종한/[lecture15] concurrency control 기초 (serializability)/not conflict equivalent1,4.png
  심종한/[lecture15] concurrency control 기초 (serializability)/not conflict equivalent2,4.png
  심종한/[lecture15] concurrency control 기초 (serializability)/schedule equivalent.png
  심종한/[lecture15] concurrency control 기초 (serializability)/스케줄.png
  심종한/[lecture16] concurrency control 기초 (recoverability)/README.md
  심종한/[lecture16] concurrency control 기초 (recoverability)/cascadeless schedule 문제 상황.png
  심종한/[lecture16] concurrency control 기초 (recoverability)/cascading rollback 문제 해결 롤백 예시.png
  심종한/[lecture16] concurrency control 기초 (recoverability)/cascading rollback 문제 해결책.png
  심종한/[lecture16] concurrency control 기초 (recoverability)/recoverable schedule.png
  심종한/[lecture16] concurrency control 기초 (recoverability)/strict schedule.png
  심종한/[lecture16] concurrency control 기초 (recoverability)/unrecoverable schedule.png
  심종한/[lecture17] isolation level/README.md
  심종한/[lecture17] isolation level/dirty read.png
  심종한/[lecture17] isolation level/dirty write .png
  심종한/[lecture17] isolation level/lost update.png
  심종한/[lecture17] isolation level/nonrepeatable read.png
  심종한/[lecture17] isolation level/phantom read.png
  심종한/[lecture17] isolation level/read skew.png
  심종한/[lecture17] isolation level/write skew.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl) /README.md
  심종한/[lecture18] concurrency control 기법 (lock & 2pl) /conservative 2PL.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl) /dead lock.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl) /expanding phase.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl) /shrinking phase.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl) /strict 2PL.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl) /strong strict 2PL.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl) /쓰기락.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl) /예상치 못한 동작이 발생할 수 있는 경우.png
Labels: size/L

#4 lecture14~18
  윤성하/[lecture14] transaction/README.md
  윤성하/[lecture15] concurrency control 기초 (serializability)/README.md
  윤성하/[lecture16] concurrency control 기초 (recoverability)/README.md
  윤성하/[lecture17] isolation level/README.md
  윤성하/[lecture18] concurrency control 기법 (lock & 2pl)/README.md
  윤성하/img/2pl_1.png
  윤성하/img/2pl_2.png
  윤성하/img/conflict.png
  윤성하/img/conservative_2pl.png
  윤성하/img/dirty_read_expand.png
  윤성하/img/dirty_write.png
  윤성하/img/lock.png
  윤성하/img/lost_update.png
  윤성하/img/read_skew.png
  윤성하/img/schedule.png
  윤성하/img/strict_2pl.png
  윤성하/img/strong_strict_2pl.png
  윤성하/img/tx1.png
  윤성하/img/tx2.png
  윤성하/img/unrecoverable_schedule.png
  윤성하/img/write_skew.png
Labels: size/L

#3 lecture14~18
  김연욱/[lecture14] transaction/README.md
  김연욱/[lecture15] concurrency control 기초 (serializability)/README.md
  김연욱/[lecture15] concurrency control 기초 (serializability)/img/lecture15-1.png
  김연욱/[lecture16] concurrency control 기초 (recoverability)/README.md
  김연욱/[lecture17] isolation level/README.md
  김연욱/[lecture18] concurrency control 기법 (lock & 2pl)/README.md
Labels: size/L

#2 lecture14~18
  서지흔/[lecture14] transaction/README.md
  서지흔/[lecture15] concurrency control 기초 (serializability)/README.md
  서지흔/[lecture16] concurrency control 기초 (recoverability)/README.md
  서지흔/[lecture17] isolation level/README.md
  서지흔/[lecture18] concurrency control 기법 (lock & 2pl)/README.md
  서지흔/img/lec17-isolationlevel.png
  서지흔/img/lec18-deadlock.png
  서지흔/img/lec18-lockerror.png
Labels: size/M

#9 lecture14~18
  심종한/[lecture18] concurrency control 기법 (lock & 2pl)/README.md
  심종한/[lecture18] concurrency control 기법 (lock & 2pl)/conservative 2PL.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl)/dead lock.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl)/expanding phase.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl)/shrinking phase.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl)/strict 2PL.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl)/strong strict 2PL.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl)/쓰기락.png
  심종한/[lecture18] concurrency control 기법 (lock & 2pl)/예상치 못한 동작이 발생할 수 있는 경우.png
Labels: size/XS
